export const MILLISECONDS_PER_SECOND = 1000;
export const SECOND_PER_MINUTE = 60;
export const MINUTES_PER_HOUR = 60;
export const BASIC_READING_AND_WRITING_TEST_TIME = 32 * SECOND_PER_MINUTE;
export const BASIC_MATH_TEST_TIME = 35 * SECOND_PER_MINUTE;
export const BASIC_BREAK_TIME = 10 * SECOND_PER_MINUTE;
